dockerfile to build a docker image with SOLVCON.
solvcon/pastsolvcon pull request #172
Opened 2016-10-29 15:55 UTC by tai271828

# Description

This commit adds a dockerfile to build a docker image with SOLVCON. The dockerfile could be used as a part of quick infrastructure to prepare SOLVCON runtime or development environment, e.g. a container-based cluster.

To put and maintain this dockerfile here is better rather than solvcon-gce, because this dockerfile could be run on local machine. For example, a user may run its example on his/her own local machine to verify his/her code or a real SOLVCON case. Please let me know if you think solvcon-gce is a better choice rather than SOLVCON.

# Test Case

Go to where this dockerfile is, and then run the command:

```
docker build -t <your docker repository name>:<your docker tag name> .
```

And then verify it with

```
docker run <your docker repository name>:<your docker tag name> bash -c "source /home/solvcon/miniconda/bin/activate; nosetests /home/solvcon/solvcon/"
```

# Expected Result

docker should report the usual SOLVCON nosetests result like

```
...................................................................................................................................................................................................................................................................................SSS
----------------------------------------------------------------------
Ran 278 tests in 4.759s

OK (SKIP=3)
```

Besides, you should have one more docker image. Confirm this by `docker images`.

2016-10-29 15:57 UTC, tai271828 commented on contrib/dockerfile
> +RUN cd ${DOCKER_SCSRC}; /bin/bash -c "source activate; python setup.py build_ext --inplace"
This ``bash -c`` looks not so graceful. docker uses ``sh`` instead of ``bash`` by default and no ``source`` command could be used.

2016-10-29 23:06 UTC, yungyuc commented on contrib/dockerfile
> +RUN cd ${DOCKER_SCSRC}; /bin/bash -c "source activate; python setup.py build_ext --inplace"
I prefer bash to sh.  SOLVCON uses a lot of modern components like the latest Python 3 (I am waiting for 3.6 release) and C++11.  I expect systems support them should also support bash.

2016-10-29 23:07 UTC, yungyuc commented on contrib/dockerfile
> +RUN useradd -m solvcon
I like it.

2016-10-29 23:08 UTC, yungyuc commented
Too bad pybind11 fails the build.  I am fixing it.

2016-10-30 00:00 UTC, yungyuc requested changes
Could you organize the comments (test cases and expected results) you put in the PR to the file itself?

2016-10-30 01:00 UTC, tai271828 commented
Resubmit the PR to add the comments in the dockerfile. Please review it.

2016-10-30 01:31 UTC, yungyuc commented
I didn't compare word by word, but it seems you copied everything from the PR description?  The "... commit ..." looks out of place inside the file.  Could you please do some organization / editing?

2016-10-30 01:34 UTC, yungyuc commented
And please insert a white space between remark texts and the leading dial mark.

2016-10-30 07:06 UTC, tai271828 commented
Thanks for the reminder. I fixed the comment block including

* to tweak the contents to make it fit into the description of the dockerfile better.
* to add the space between remark texts and the leading dial mark.

2016-10-30 07:52 UTC, merged