Pr sod utest
solvcon/pastsolvcon pull request #186
Opened 2017-07-01 09:18 UTC by tai271828

Add a Sod tube nosetest example

This nosetest will provide a Sod tube simulation data and compare the data with 1D analytic solutions.

This pull request provides a nosetest based on the previous sandbox [Sod tube driving script] (https://github.com/solvcon/solvcon/blob/master/sandbox/gas/tube/go) with some different parameters. That is, this nosetest will run its own case, which differs from the sandbox driving script including

* This nosetest case removes unnecessary hooks (e.g. CFL hook) and reserves the hooks to generate data.
* This nosetest case use different edgelength, time_increment and steps_run to get higher CFL.
* This nosetest case is not launched over the sc command interface, but an explicit case registered to the arrangements.

To validate the SOLVCON data, this nosetest uses 1D anlytic solution as benchmark. It compares the numeric data with two ways:

* The so-called **counter** method
* The so-called **snapshot** method

# Counter Method

The regions adjacent discontinuities are likely to deviate much from analytic solutions. However, these data should be match the analytic solutions soon after few time iteration steps. The so-called counter comparison method does not regard the comparison as failure unless the data deviates from the analytic solutions many times in a time period.

# Snapshot method

The snapshot method watches the final status of the numeric solutions and compare them to the analytic solutions. However, the snapshot method only picks up some of the locations which are not nearby the discontinuity region to watch, so it could avoid to compare the discontinuities.

# File Hierarchy

The commit https://github.com/tai271828/solvcon/commit/0a5b1e7389c5f572a00168d650f443d82f315792 introduces this new test example. It also shows the file hierarchy. In ``solvcon/examples/gas``

```
tests/
├── __init__.py
├── test_sod.py
└── tube
    ├── analytic.py
    ├── __init__.py
    └── sod.py
```

The other commits of this PR are auxiliary change for this "core" commit. 

# Test This PR

```
$ nosetests -v examples/gas/tests/
test_sod_tube_by_counter (tests.test_sod.TestGas) ... ok
test_sod_tube_by_snapshot (tests.test_sod.TestGas) ... ok

----------------------------------------------------------------------
Ran 2 tests in 7.721s

OK
```

# Topics Need to Discuss
## Add scipy dependency

The analytic solution uses the scipy module. Is it ok to install a module that is used by one application?

## Close Issue #128 

Issue #128 is ready to close. We can keep improving this Sod example in the future.

2017-07-02 12:34 UTC, yungyuc commented
I am not aware of the "so-call" counter and snapshot methods.  Could you provide a reference for them?

For estimating error, a common practice is to use norm.  Set v(x, t) as the analytical solution and u(x, t) the numerical, the error field is e(x,t) = u(x,t) - v(x,t).  At any given time the norm of the error function can be calculated as L(t) = |e(x,t)|.  L_0, L_1, and L_2 are commonly used norms.

If we want to exclude the error around the discontinuity, those values around it may be exempted from the error field.  Thus we get the modified error function e'(x,t) = E(u(x,t) - v(x,t)) where E excludes the values around discontinuity.

2017-07-02 12:40 UTC, yungyuc requested changes

2017-07-02 12:40 UTC, yungyuc commented on examples/gas/tests/tube/sod.py
> +    :ivar
Redundant fields.

2017-07-02 12:40 UTC, yungyuc commented on examples/gas/tests/test_sod.py
> +    sod.run()
Why run this at the class level?  `sod.run()` doesn't return anything or set global variables.

2017-07-02 12:40 UTC, yungyuc commented on solvcon/parcel/gas/probe.py
> +            point_name = format_character % int(point.name)
This looks like a bad idea since point.name isn't necessarily an integer.

2017-07-03 00:38 UTC, tai271828 commented
The terms **counter method** and **snapshot method** are invented by myself. They are de facto L2 norm of the error function. Their names indicate that they adapt different algorithms to exclude the error around the discontinuity.

Your comment inspires me to implement one more intuitive and easier understanding test algorithm: use the analytic solution to get the coordinates of the discontinuity which is moving when time goes by, and then exclude the data around them.

Regarding the report, I will only say how close it is to the analytic solution, but not a "correct" result. For example, I noted this driving script gives npy binary files with different floating point numbers. I will write a report and check a bit why the npy files are not identical (by investigating a question like "does the deviation come from the discontinuity?") What do you think if this report just describe how close the numeric solution is to the analytic solution? Do you think it is enough so far?

2017-07-03 02:27 UTC, yungyuc commented
Regarding the report, something shows your results in graphics will be good enough.  It's quite difficult to understand what the code does without graphics.

2017-07-30 09:04 UTC, closed without merging