Include a build script for Singularity file
solvcon/pastsolvcon pull request #216
Opened 2018-09-13 02:41 UTC by tai271828

Append the missing build script for careless git operation. This commit is a part of this PR https://github.com/solvcon/solvcon/pull/215

2018-09-13 03:03 UTC, yungyuc requested changes
For download and build file removal, perhaps you can use an option to toggle.  When debugging the build scripts the intermediate files are useful.

2018-09-13 03:03 UTC, yungyuc commented on contrib/singularity/prepare-solvcon-dev.sh
> +
How about removing the downloaded files here, so that the built singularity image doesn’t contain them and bloat?

2018-09-13 03:03 UTC, yungyuc commented on contrib/singularity/prepare-solvcon-dev.sh
> +
Remove down'oaded and intermediate build files too.

2018-09-13 03:03 UTC, yungyuc commented on contrib/singularity/prepare-solvcon-dev.sh
> +
Probably make clean to remove the intermediate build files?

2018-09-14 02:07 UTC, tai271828 commented
Both of debugging and cleaning idea are good idea. I will implement them.

2018-09-14 15:09 UTC, yungyuc requested changes

2018-09-14 15:09 UTC, yungyuc commented on contrib/singularity/prepare-solvcon-dev.sh
> +rm -rf ${MINICONDA_DIR}/build
Remove also `${MINICONDA_DIR}/pkgs`, which is the cache directory for packages.

2018-09-14 15:10 UTC, yungyuc commented
Could you make the change history a straight line?  You merged from master and the history looks unnecessary complex.  Probably rebase?

2018-09-15 05:11 UTC, tai271828 commented
Will rebase. The change for this PR has not been completed, and I should not push it to the branch to make you confused. Sorry for wasting your time.

2018-09-15 09:45 UTC, yungyuc commented
My apology if I sounded discontent.  I appreciate your contribution.  You don't need to clean up the history before the PR is ready for merging.  My comment was meant to be an early reminder.

2018-09-17 17:16 UTC, tai271828 commented
Hi, the PR is ready to review.

To integrate a debug option is more complex than I expected, I would suggest us to stop at removing intermediate files for now, and enhance the debug feature in another PR, so it will be easier to review and maintain in the future.

Besides, please note I add one more script ``build-solvcon.sh``. It is a wrapper. Run it to verify this PR. You may be interested in reading the associated updated README. By using ``build-solvcon.sh``, you could easily run your driving script. Try a `singularity exec ...` command which is shown at the end of ``build-solvcon.sh`` build process as an example for you to run your driving script.

2018-09-18 02:49 UTC, yungyuc approved these changes

2018-09-18 02:50 UTC, yungyuc commented
Yes, it's good.   Thanks a lot.  Merging.

2018-09-18 02:50 UTC, merged